name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
        working-directory: ./app

      - run: npm run build --if-present
        working-directory: ./app

      - run: CI=true npm test
        working-directory: ./app