name: Node.js CI

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: "3"
  TF_VERSION: 1.6.4

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: npm ci
        working-directory: ./app

      - run: npm run build --if-present
        working-directory: ./app

      - run: npm test
        working-directory: ./app

  terraform:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials_json: ${{ secrets.DEPLOY_KEY_FILE }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: true

      - name: Terraform Init
        id: init
        run: terraform init -upgrade
        working-directory: terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="deployment_version=deploy-${GITHUB_SHA::6}"
        working-directory: terraform

      # - run: echo ${GITHUB_SHA::6}

  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials_json: ${{ secrets.DEPLOY_KEY_FILE }}

      - run: terraform plan -var="deployment_version=deploy-${GITHUB_SHA::6}"

      # - name: Terraform Apply
      #   id: plan
      #   run: terraform plan -var="deployment_version=deploy-${GITHUB_SHA::6}"
      #   working-directory: terraform

  #     - name: gcloud deploy appengine
  #       id: deploy-appengine
  #       uses: google-github-actions/deploy-appengine@v1
  #       with:
  #         working_directory: app

  #     - name: 'Verify deployment'
  #       run: |-
  #         curl '${{ steps.deploy-appengine.outputs.url }}' \
  #           --silent \
  #           --fail \
  #           --location \
  #           --retry 5 \
  #           --retry-connrefused \
  #           --retry-delay 5 \
  #           --retry-max-time 300
